name: clinic_appointment_chatbot
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  cupertino_icons: ^1.0.2
  dialog_flowtter: ^0.3.3
  flutter:
    sdk: flutter
  
  flutter_native_splash: ^2.2.16
  google_fonts: ^3.0.1
  loading_animation_widget: ^1.2.0+4
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon.png"


flutter:

  uses-material-design: true

  assets:
    - assets/
  